const { ipcRenderer } = require('electron');
const { Howl } = require('howler');
const metadata = require('music-metadata');
const storage = require('electron-json-storage');
const { seconds_to_time } = require('../../Util/convert');
const random = require('../../Util/random');
const rpc = require('discord-rpc');
const client = new rpc.Client({transport:'ipc'});
client.login({ clientId:'952501026584416337'});
const os = require('os');
storage.setDataPath(os.homedir() + '/playlist/');
global.ipcRenderer = ipcRenderer;
global.Howl = Howl;
global.mm = metadata;
global.storage = storage;
global.seconds_to_time = seconds_to_time;
global.random = random;
global.client = client;
global.pid = process.pid;
