const { ipcRenderer } = require('electron');
const { Howl } = require('howler');
const metadata = require('music-metadata');
const { seconds_to_time } = require('../../Util/convert');
const random = require('../../Util/random');
const fs = require('fs');
const util = require('util');
const rpc = require('discord-rpc');
const client = new rpc.Client({transport:'ipc'});
client.login({ clientId:'952501026584416337'});
global.ipcRenderer = ipcRenderer;
global.Howl = Howl;
global.mm = metadata;
global.seconds_to_time = seconds_to_time;
global.random = random;
global.fs = fs;
global.util = util;
global.client = client;