name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2019]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Package prebuild
        run: npm run build
        if: "!(matrix.os == 'macos-12')"
      - name: Package prebuild (macOS)
        run: npm run build:mac
        if: matrix.os == 'macos-12'