name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2019]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Package prebuild
        run: npm run build
        if: "!(matrix.os == macos-12)"
      
      - name: Package prebuild
        run: npm run build:mac
        if: matrix.os == macos-12

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: out/make/

  upload-assets:
    name: Upload Assets
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ always() }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Flatten directory
        run: |
          mkdir release
          find ./ -mindepth 2 -type f -exec mv -t ./release -n '{}' +

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: './release/*'
